---
title: "chapter2"
author: "Femke Thon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r}
library(plot.practice)
library(ggplot2)
```
First we run the stuff I wrote down.

```{r}
result <- chapter2()
names(result)
names(result$plots)
```
## Results

Then we look at what I generated using this function.

For starters, I generated some data from an existing dataset.

```{r}
result$data
```

And plotted some of it.

```{r}
result$plots$plot
result$plots$logplot
result$plots$xyzplot
result$plots$coloured
```

I don't know why these won't work, but hey, when I run the function manually,
they do.

```{r}
result$plots$shapes
result$plots$red
result$plots$alpha
result$plots$smooth1
result$plots$smooth2
result$plots$density
result$plots$histo1
result$plots$histo2
result$plots$histo3
result$plots$bar
result$plots$time
result$plots$path
result$plots$facets
result$plots$more
```

So those were the things I tried while reading chapter 2.
